### ISSUE TITLE
Trenger muligheten til å oppdatere et produkt i katalogen

### ISSUE THREAD

**Issue by Arefgol** [Arefgol/Agile-Porsjekt#3]
**Som en** administrator
**Trenger jeg** muligheten til å oppdatere et produkt i katalogen
**Slik at** jeg kan holde produktinformasjonen oppdatert og korrekt for kundene.

 ### Details and Assumptions
* [document what you know]

### Acceptance Criteria 9.
 ```gherkin
**Given jeg er innlogget som produktadministrator
**When jeg går til "Legg til produkt"-siden
  And fyller ut nødvendig produktinformasjon (navn, beskrivelse, pris)
  And klikker på "Opprett produkt"
**Then skal produktet legges til i katalogen
  And produktet skal være synlig for kundene i produktlisten.

**Comment by Shirazish** [comment]
Vi må se nærmere på dette. Jeg kaller inn til et møte for å forklare hva vi ønsker.
